name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: '3.x' 
        architecture: 'x64' # (x64 or x86)

    - name: Install Pandoc
      run: |
        mkdir -p /tmp/pandoc
        cd /tmp/pandoc
        python -m pip --no-cache-dir install setuptools wheel
        python -m pip --no-cache-dir install pandocfilters Pygments
        sudo apt install -y texlive texlive-xetex latexmk wget
        wget -q "https://github.com/jgm/pandoc/releases/download/3.1.6.1/pandoc-3.1.6.1-1-amd64.deb"
        sudo dpkg -i pandoc-3.1.6.1-1-amd64.deb
        rm -rf *.deb

    - name: Install Fonts
      run: |
        mkdir -p /tmp/adodefont
        cd /tmp/adodefont
        wget -q -O source-code-pro.zip https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
        wget -q -O source-han-serif.zip https://github.com/adobe-fonts/source-han-serif/archive/1.001R.zip
        wget -q -O source-han-sans.zip https://github.com/adobe-fonts/source-han-sans/archive/2.001R.zip
        unzip -q source-code-pro.zip -d source-code-pro
        unzip -q source-han-serif.zip -d source-han-serif
        unzip -q source-han-sans.zip -d source-han-sans
        mkdir -p ~/.fonts
        cp -v source-code-pro/*/OTF/*.otf ~/.fonts/
        cp -v source-han-serif/*/SubsetOTF/*/*.otf ~/.fonts/
        cp -v source-han-sans/*/SubsetOTF/*/*.otf ~/.fonts/
        fc-cache -f
        rm -rf source-code-pro{,.zip} source-han-serif{,.zip} source-han-sans{,.zip}

    - name: Generate PDF
      run: |
        mkdir -p ~/.pandoc/templates
        cp pandoc/algo.latex ~/.pandoc/templates/
        sh pandoc/gen.sh
        mkdir build
        cp template.pdf build/template.pdf

    - name: Release
      uses: JamesIves/github-pages-deploy-action@3.6.2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages 
        FOLDER: build
        CLEAN: false 

